services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: otp-app:latest
    env_file:
      - .env.example
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      - redis
      - migrate
    healthcheck:
      test: ["CMD-SHELL", "php -r 'exit((int)!@fsockopen(\"127.0.0.1\", 9000));'"]
      interval: 5s
      timeout: 3s
      retries: 20

  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: otp-web:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
    depends_on:
      app:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d laravel"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    ports:
      - "6389:6379"

  migrate:
    image: otp-app:latest
    env_file:
      - .env.example
    volumes:
      - ./:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    command: php artisan migrate --force --no-interaction
    restart: "no"

volumes:
  db-data:


