services:
  api:
    container_name: ${PROJECT_BASE_NAME}
    build:
      context: ./landing
      dockerfile: .docker/php.dockerfile
    volumes:
      - ./landing/storage/app:/app/storage/app:cached
    depends_on:
      - mysql
      - redis
    ports:
      - ${API_PORT:-9010}:8000
    networks:
      - ${NETWORK_NAME}
  mysql:
    image: mysql:8.0
    restart: always
    container_name: ${PROJECT_BASE_NAME}-mysql
    volumes:
      - ./.docker/mysql:/var/lib/mysql
      - ./.docker/mysql-backups:/var/backups
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - ${NETWORK_NAME}
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin:5.2
    restart: no
    container_name: ${PROJECT_BASE_NAME}-pma
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${PMA_PORT:-9015}:80
    networks:
      - ${NETWORK_NAME}
  redis:
    image: redis:7.0
    container_name: ${PROJECT_BASE_NAME}-redis
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./.docker/redis:/data
    networks:
      - ${NETWORK_NAME}
  supervisor:
    build:
      context: ./landing
      dockerfile: supervisor.prod.dockerfile
    container_name: ${PROJECT_BASE_NAME}-supervisor
    volumes:
      - ./landing/storage:/var/www/api/storage
      - ./landing/.docker/supervisord/supervisor.conf:/etc/supervisor/supervisord.conf
    depends_on:
      - redis
    networks:
      - ${NETWORK_NAME}

networks:
  goldab:
